import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { query } = await req.json();
    
    if (!query || typeof query !== 'string') {
      return new Response(
        JSON.stringify({ error: 'กรุณาระบุคำถามที่ต้องการค้นหา' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    const SUPABASE_URL = Deno.env.get('SUPABASE_URL');
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

    if (!LOVABLE_API_KEY || !SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error('Required environment variables are not configured');
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    console.log('Processing query:', query);

    // First, let AI understand the query and generate SQL filter conditions
    const systemPrompt = `คุณคือผู้ช่วยค้นหาข้อมูลผู้ประสบภัยน้ำท่วม 
ฐานข้อมูลมีฟิลด์:
- name (ชื่อ)
- lastname (นามสกุล)
- address (ที่อยู่)
- phone (เบอร์โทร array)
- number_of_adults (จำนวนผู้ใหญ่)
- number_of_children (จำนวนเด็ก)
- number_of_seniors (จำนวนผู้สูงอายุ)
- health_condition (ภาวะสุขภาพ)
- help_needed (ความช่วยเหลือที่ต้องการ)
- urgency_level (1-5)
- status (pending/helped)

วิเคราะห์คำถามและบอกว่าต้องกรองข้อมูลอย่างไร`;

    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: query }
        ],
        tools: [
          {
            type: 'function',
            function: {
              name: 'generate_filter',
              description: 'สร้างเงื่อนไขการค้นหาข้อมูล',
              parameters: {
                type: 'object',
                properties: {
                  urgency_level: { 
                    type: 'integer',
                    description: 'ระดับความเร่งด่วน (1-5)'
                  },
                  has_children: { 
                    type: 'boolean',
                    description: 'มีเด็กหรือไม่'
                  },
                  has_seniors: { 
                    type: 'boolean',
                    description: 'มีผู้สูงอายุหรือไม่'
                  },
                  province: { 
                    type: 'string',
                    description: 'จังหวัด (ถ้ามีระบุในคำถาม)'
                  },
                  help_type: { 
                    type: 'string',
                    description: 'ประเภทความช่วยเหลือที่ต้องการ เช่น เรือ อาหาร'
                  },
                  status: {
                    type: 'string',
                    description: 'สถานะ pending หรือ helped'
                  }
                },
                additionalProperties: false
              }
            }
          }
        ],
        tool_choice: { type: 'function', function: { name: 'generate_filter' } }
      }),
    });

    if (!aiResponse.ok) {
      throw new Error(`AI Gateway error: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    const toolCall = aiData.choices?.[0]?.message?.tool_calls?.[0];
    
    if (!toolCall) {
      throw new Error('No filter generated by AI');
    }

    const filters = JSON.parse(toolCall.function.arguments);
    console.log('Generated filters:', filters);

    // Build Supabase query based on filters
    let supabaseQuery = supabase.from('reports').select('*');

    if (filters.urgency_level) {
      supabaseQuery = supabaseQuery.eq('urgency_level', filters.urgency_level);
    }

    if (filters.has_children) {
      supabaseQuery = supabaseQuery.gt('number_of_children', 0);
    }

    if (filters.has_seniors) {
      supabaseQuery = supabaseQuery.gt('number_of_seniors', 0);
    }

    if (filters.province) {
      supabaseQuery = supabaseQuery.ilike('address', `%${filters.province}%`);
    }

    if (filters.help_type) {
      supabaseQuery = supabaseQuery.ilike('help_needed', `%${filters.help_type}%`);
    }

    if (filters.status) {
      supabaseQuery = supabaseQuery.eq('status', filters.status);
    }

    supabaseQuery = supabaseQuery.order('urgency_level', { ascending: false }).order('created_at', { ascending: false }).limit(50);

    const { data: reports, error: dbError } = await supabaseQuery;

    if (dbError) {
      console.error('Database error:', dbError);
      throw new Error('ไม่สามารถค้นหาข้อมูลได้');
    }

    console.log(`Found ${reports?.length || 0} reports`);

    // Generate natural language response
    const summaryResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { 
            role: 'system', 
            content: 'คุณคือผู้ช่วยสรุปข้อมูลผู้ประสบภัย ตอบเป็นภาษาไทยที่เข้าใจง่าย กระชับ และเป็นมิตร' 
          },
          { 
            role: 'user', 
            content: `คำถาม: ${query}\n\nพบข้อมูล ${reports?.length || 0} รายการ\n\nสรุปข้อมูลสำคัญให้กับผู้ใช้` 
          }
        ],
      }),
    });

    const summaryData = await summaryResponse.json();
    const summary = summaryData.choices?.[0]?.message?.content || `พบข้อมูล ${reports?.length || 0} รายการ`;

    return new Response(
      JSON.stringify({ 
        summary,
        count: reports?.length || 0,
        reports: reports || []
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in query-reports function:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'เกิดข้อผิดพลาดในการค้นหา' 
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});